[build]
  command = "astro build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "astro dev"
  targetPort = 4321
  port = 8888

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Disposition = "inline"
    Content-Type = "application/pdf"

